--cod rau: SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--cod bun: TRANSACTION ISOLATION LEVEL SERIALIZABLE 

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
	select * from Tari
	WAITFOR DELAY '00:00:10'
	select * from Tari
COMMIT TRANSACTION

--select * from Tari